# 玩家监控设置
monitor:
  # 定时器检查周期 (tick)，数值越小，BOSS 血条更新越流畅
  timer-interval: 2
  # 在玩家切换世界后多久 (tick)，再设置玩家的旁观目标
  # 如果在玩家传送到另一个世界后旁观者模式有问题，请将这个数值调大
  teleport-delay: 5
  # 每个玩家的观察时间 (秒)
  watch-seconds-per-player: 10.0
  # BOSS 血条设置，将 title 选项注释或留空，则关闭 BOSS 血条功能
  camera-bossbar:
    # 可用时间变量
    # %time%, %time_int% 正常时间
    # %time_reversed%, %time_reversed_int% 倒计时
    title: '&c👁 &f正在视奸&e %player_name%&f，剩余 %time_reversed%s &c👁'
    # 只剩一人时
    last-one: '&c👁 &f正在视奸&e %player_name% &c👁'
    # 没有玩家时
    empty: '&f暂无可视奸的玩家'
    # 血条颜色，可用颜色请到以下链接查看
    # https://javadoc.mcio.dev/spigot/1.21.4/org/bukkit/boss/BarColor.html
    color: WHITE
    # 血条样式，可用样式请到以下链接查看
    # https://javadoc.mcio.dev/spigot/1.21.4/org/bukkit/boss/BarStyle.html
    style: SOLID
    # 进度是否反向
    # true  -- 血条随时间递减
    # false -- 血条随时间递增
    reversed: true
  # 指定玩家不会被视奸
  blacklist:
    - Herobrine
  # 只有指定玩家会被视奸，留空则不开启该功能
  # 开启该功能会禁用下方的不活跃检查功能，也会禁用权限检查功能，但 blacklist 依然会生效
  whitelist: []
  # 在一段时间内不活跃的玩家，不会被视奸
  ignore-inactive:
    # 在玩家执行什么操作的时候，视为活跃
    # 默认为 移动、攻击、挥动手臂
    enable:
      - MOVE
      - ATTACK
      - ANIMATION
    # 需要设定的时间 (秒)
    # 设为 0 则关闭该功能
    seconds: 300.0
